ORDER_BOOK_DEPTH20_100MS_ENDPOINT = "wss://fstream.binance.com/ws/btcusdt@depth20@100ms"
OPEN_ORDER_ENDPOINT = "https://fapi.binance.com/fapi/v1/order"

MINIMUM_PRICE_CHANGE_TO_SHORT = -0.5
MINIMUM_PRICE_CHANGE_TO_LONG = LOW_VOLUME = 0.5

LOWEST_QUANTITY = 0.999
MAX_DEPTH_OF_ORDER_BOOK = 10

PRICE = FIRST_PRICE = DEPTH_TYPE = FIRST_LIMIT_PRICE_WITH_QUANTITY = 0

TRAILING_STOP_GAP = 1.5  # in dollars
LARGE_POSITION_INDEX_IN_DEPTH = 1
SECOND_LIMIT_PRICE_WITH_QUANTITY = 1